### ISSUE TITLE
[Deploy] Github Actions Workflows 및 issue, pr 템플릿 추가

### ISSUE THREAD

**Issue by junseoplee** [CMC-16th-TeamU/MZ_Gen-s_Regret_Server#1]
## 📑 작업 사항
개발 및 배포 관련 작업 설정

## To-do
- [x] Github Actions workflow 추가
- [x] 이슈 및 pr 템플릿 추가
- [x] 필요한 의존성 추가

## ETC
기타 사항을 작성해 주세요.
